Update apt.pp - Avoid Source conflict with sensu
Source conflict with sensu puppet module. - Also requested in the sensu module 
```
Error: Duplicate declaration: Apt::Source[sensu] is already declared in file /tmp/vagrant-puppet-3/modules-0/uchiwa/manifests/repo/apt.pp:34; cannot redeclare at /tmp/vagrant-puppet-3/modules-0/sensu/manifests/repo/apt.pp:35
```